SELECT * FROM PROJETOS;

SELECT * FROM DONATARIOS;

SELECT DOACOES.ID_DOACAO, DOACOES.VALOR, DOACOES.DATA, DOACOES.TIPO_DOACAO, PROJETOS.NOME_PROJETO
FROM DOACOES
JOIN PROJETOS ON DOACOES.ID_PROJETO = PROJETOS.ID_PROJETO;

SELECT RELATORIO.ID_RELATORIO, RELATORIO.DATA_ENVIO, RELATORIO.TIPO_RELATORIO, PROJETOS.NOME_PROJETO
FROM RELATORIO
JOIN PROJETOS ON RELATORIO.ID_PROJETO = PROJETOS.ID_PROJETO;

SELECT * FROM EDITAL;

SELECT * FROM COMISSAO;

SELECT PROJETOS.NOME_PROJETO, COMISSAO.NOME_MEMBRO, COMISSAO.CARGO
FROM PROJETOS_COMISSAO
JOIN PROJETOS ON PROJETOS_COMISSAO.ID_PROJETO = PROJETOS.ID_PROJETO
JOIN COMISSAO ON PROJETOS_COMISSAO.ID_COMISSAO = COMISSAO.ID_COMISSAO;

SELECT * FROM PROJETOS
WHERE STATUS = 'Em Andamento';

SELECT * FROM DONATARIOS
WHERE TIPO_DONATARIO = 'Privada';

SELECT PROJETOS.NOME_PROJETO, COUNT(DOACOES.ID_DOACAO) AS NUMERO_DOACOES
FROM DOACOES
JOIN PROJETOS ON DOACOES.ID_PROJETO = PROJETOS.ID_PROJETO
GROUP BY PROJETOS.NOME_PROJETO;
