
CREATE DATABASE ESTCASO_3;


USE ESTCASO_3;




CREATE TABLE IF NOT EXISTS CLIENTES(
    COD_CLIENTE INT PRIMARY KEY,
    CNPJ INT NOT NULL,
    RAZAO_SOCIAL VARCHAR(45) NOT NULL,
    RAMO_ATV VARCHAR(45) NOT NULL,
    DATA_CADASTRO DATE NOT NULL,
    PESSOA_CONTATO VARCHAR(30) NOT NULL
);


ALTER TABLE CLIENTES ADD IDADE VARCHAR(12) NOT NULL;
ALTER TABLE CLIENTES MODIFY COLUMN IDADE DATETIME NOT NULL;
ALTER TABLE CLIENTES CHANGE COLUMN IDADE DATA_NASCIMENTO DATETIME NOT NULL;
ALTER TABLE CLIENTES DROP COLUMN DATA_NASCIMENTO;



CREATE TABLE IF NOT EXISTS EMPREGADOS(
    COD_MATRICULA INT PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    CARGO VARCHAR(45) NOT NULL,
    SALARIO VARCHAR(9) NOT NULL,
    DATA_ADESAO DATE NOT NULL,
    QUALIFICACAO VARCHAR(30) NOT NULL
);


ALTER TABLE EMPREGADOS ADD IDADE VARCHAR(12) NOT NULL;
ALTER TABLE EMPREGADOS MODIFY COLUMN IDADE DATETIME NOT NULL;
ALTER TABLE EMPREGADOS CHANGE COLUMN IDADE DATA_NASCIMENTO DATETIME NOT NULL;
ALTER TABLE EMPREGADOS DROP COLUMN DATA_NASCIMENTO;



CREATE TABLE IF NOT EXISTS FORNECEDORES(
    CNPJ INT PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(45) NOT NULL,
    PESSOA_CONTATO VARCHAR(45) NOT NULL
);


ALTER TABLE FORNECEDORES ADD NUM_ENDERECO VARCHAR(12) NOT NULL;
ALTER TABLE FORNECEDORES MODIFY COLUMN NUM_ENDERECO INT;
ALTER TABLE FORNECEDORES CHANGE COLUMN NUM_ENDERECO UNIDADE INT;
ALTER TABLE FORNECEDORES DROP COLUMN UNIDADE;



CREATE TABLE IF NOT EXISTS MAQUINAS(
    COD_MAQUINA INT PRIMARY KEY,
    TEMPO_VIDA DATETIME NOT NULL,
    DATA_COMPRA DATE NOT NULL,
    DATA_FIM_GARANTIA DATE NOT NULL
);


ALTER TABLE MAQUINAS ADD NOME_MAQUINA VARCHAR(12) NOT NULL;
ALTER TABLE MAQUINAS MODIFY COLUMN NOME_MAQUINA VARCHAR(20) NOT NULL;
ALTER TABLE MAQUINAS CHANGE COLUMN NOME_MAQUINA USO_MAQUINA VARCHAR(45) NOT NULL;
ALTER TABLE MAQUINAS DROP COLUMN USO_MAQUINA;



CREATE TABLE IF NOT EXISTS RE(
    COD_RECURSO INT PRIMARY KEY,
    QNTD_NECESSARIA INT,
    UNIDADE VARCHAR(30) NOT NULL,
    TEMPO_USO DATETIME NOT NULL,
    MAO_DE_OBRA VARCHAR(25) NOT NULL
);


ALTER TABLE RE ADD NOME_RECURSO VARCHAR(12) NOT NULL;
ALTER TABLE RE MODIFY COLUMN NOME_RECURSO VARCHAR(20) NOT NULL;
ALTER TABLE RE CHANGE COLUMN NOME_RECURSO USO_RECURSO VARCHAR(20) NOT NULL;
ALTER TABLE RE DROP COLUMN USO_RECURSO;



CREATE TABLE IF NOT EXISTS RS(
    COD_SUPRIMENTO INT PRIMARY KEY,
    QNTD INT,
    DATA_NECESSIDADE DATE NOT NULL
);


ALTER TABLE RS ADD NOME_SUPRIMENTO VARCHAR(12) NOT NULL;
ALTER TABLE RS MODIFY COLUMN NOME_SUPRIMENTO VARCHAR(20);
ALTER TABLE RS CHANGE COLUMN NOME_SUPRIMENTO USO_SUPRIMENTO VARCHAR(20) NOT NULL;
ALTER TABLE RS DROP COLUMN USO_SUPRIMENTO;



CREATE TABLE IF NOT EXISTS TELEFONES(
    COD_TELEFONE INT PRIMARY KEY,
    NUM_TELEFONE VARCHAR(15) NOT NULL,
    COD_CLIENTE INT,
    CONSTRAINT FK_CLIENTE FOREIGN KEY(COD_CLIENTE) REFERENCES clientes(COD_CLIENTE)
);


ALTER TABLE TELEFONES ADD NOME_TELEFONE VARCHAR(12) NOT NULL;
ALTER TABLE TELEFONES MODIFY COLUMN NOME_TELEFONE VARCHAR(20) NOT NULL;
ALTER TABLE TELEFONES CHANGE COLUMN NOME_TELEFONE USO_TELEFONE VARCHAR(20) NOT NULL;
ALTER TABLE TELEFONES DROP COLUMN USO_TELEFONE;



CREATE TABLE IF NOT EXISTS ENDERECOS(
    COD_ENDERECO INT PRIMARY KEY,
    UF VARCHAR(2) NOT NULL,
    CEP VARCHAR(11) NOT NULL,
    CIDADE VARCHAR(45) NOT NULL,
    BAIRRO VARCHAR(45) NOT NULL,
    LOGRADOURO VARCHAR(45) NOT NULL,
    COMPLEMENTO VARCHAR(45) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    COD_CLIENTE INT,
    COD_MATRICULA INT,
    CNPJ INT,
    CONSTRAINT FK_CLIENTE_ENDERECO FOREIGN KEY(COD_CLIENTE) REFERENCES CLIENTES(COD_CLIENTE),
    CONSTRAINT FK_EMPREGADO FOREIGN KEY(COD_MATRICULA) REFERENCES EMPREGADOS(COD_MATRICULA),
    CONSTRAINT FK_FORNECEDOR FOREIGN KEY(CNPJ) REFERENCES FORNECEDORES(CNPJ)
);


ALTER TABLE ENDERECOS ADD NUM_ENDERECO VARCHAR(12) NOT NULL;
ALTER TABLE ENDERECOS MODIFY COLUMN NUM_ENDERECO INT;
ALTER TABLE ENDERECOS CHANGE COLUMN NUM_ENDERECO UNIDADE INT;
ALTER TABLE ENDERECOS DROP COLUMN UNIDADE;



CREATE TABLE IF NOT EXISTS TIPO_ENDERECO(
    NOME_TIPO VARCHAR(45) NOT NULL,
    COD_ENDERECO INT,
    CONSTRAINT FK_ENDERECO FOREIGN KEY
    (COD_ENDERECO) REFERENCES ENDERECOS(COD_ENDERECO)
);


ALTER TABLE TIPO_ENDERECO ADD NUM_ENDERECO VARCHAR(12) NOT NULL;
ALTER TABLE TIPO_ENDERECO MODIFY COLUMN NUM_ENDERECO INT;
ALTER TABLE TIPO_ENDERECO CHANGE COLUMN NUM_ENDERECO UNIDADE INT;
ALTER TABLE TIPO_ENDERECO DROP COLUMN UNIDADE;



CREATE TABLE IF NOT EXISTS PRODUTOS(
    COD_PRODUTO INT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(45) NOT NULL,
    TEMPO_FABRICAÇÃO DATE NOT NULL,
    PRECO_PRODUTO VARCHAR(20) NOT NULL,
    MAO_DE_OBRA VARCHAR(25) NOT NULL,
    COD_RECURSO INT,
    COD_SUPRIMENTO INT,
    COD_MAQUINA INT,
    CONSTRAINT FK_RECURSOS FOREIGN KEY(COD_RECURSO) REFERENCES RE(COD_RECURSO),
    CONSTRAINT FK_SUPRIMENTO FOREIGN KEY(COD_SUPRIMENTO) REFERENCES RS(COD_SUPRIMENTO),
    CONSTRAINT FK_MAQUINA FOREIGN KEY(COD_MAQUINA) REFERENCES MAQUINAS(COD_MAQUINA)
);


ALTER TABLE PRODUTOS ADD SUPRIMENTO_NECESSARIO VARCHAR(12) NOT NULL;
ALTER TABLE PRODUTOS MODIFY SUPRIMENTO_NECESSARIO INT;
ALTER TABLE PRODUTOS CHANGE COLUMN SUPRIMENTO_NECESSARIO ID_SUPRIMENTO INT;
ALTER TABLE PRODUTOS DROP COLUMN ID_SUPRIMENTO;



CREATE TABLE IF NOT EXISTS CARACTERISTICAS_PRODUTOS(
    DESENHO_PRODUTO VARCHAR(45) NOT NULL,
    COR_PRODUTO VARCHAR(20) NOT NULL,
    DIMENSOES_PRODUTO VARCHAR(45) NOT NULL,
    PESO_PRODUTO VARCHAR(10) NOT NULL,
    COD_PRODUTO INT,
    CONSTRAINT FK_CARAC_PRODUTO FOREIGN KEY(COD_PRODUTO) REFERENCES PRODUTOS(COD_PRODUTO)
);


ALTER TABLE CARACTERISTICAS_PRODUTOS ADD LARGURA_BORDA VARCHAR(12) NOT NULL;
ALTER TABLE CARACTERISTICAS_PRODUTOS MODIFY COLUMN LARGURA_BORDA INT;
ALTER TABLE CARACTERISTICAS_PRODUTOS CHANGE COLUMN LARGURA_BORDA TAMANHO_BORDA INT;
ALTER TABLE CARACTERISTICAS_PRODUTOS DROP COLUMN TAMANHO_BORDA;



CREATE TABLE IF NOT EXISTS ENCOMENDAS(
    COD_ENCOMENDA INT PRIMARY KEY,
    DATA_INCLUSÃO DATE NOT NULL,
    VALOR_TOTAL VARCHAR(45) NOT NULL,
    VALOR_LIQUIDO VARCHAR(45) NOT NULL,
    VALOR_DESCONTO VARCHAR(10) NOT NULL,
    QUANTIDADE_PARCELAS VARCHAR(20) NOT NULL,
    FORMA_PAGAMENTO VARCHAR(20) NOT NULL,
    COD_PRODUTO INT,
    CONSTRAINT FK_ENCOM_PRODUTO FOREIGN KEY(COD_PRODUTO) REFERENCES PRODUTOS(COD_PRODUTO)
);


ALTER TABLE ENCOMENDAS ADD TIPO_ENCOMENDA VARCHAR(12) NOT NULL;
ALTER TABLE ENCOMENDAS MODIFY COLUMN TIPO_ENCOMENDA VARCHAR(20) NOT NULL;
ALTER TABLE ENCOMENDAS CHANGE COLUMN TIPO_ENCOMENDA CARATER_ENCOMENDA VARCHAR(20) NOT NULL;
ALTER TABLE ENCOMENDAS DROP COLUMN CARATER_ENCOMENDA;



CREATE TABLE IF NOT EXISTS COMPONENTES(
    COD_COMPONENTE INT PRIMARY KEY,
    NOME_COMPONENTE VARCHAR(45) NOT NULL,
    QNTD_ESTOQUE VARCHAR(20) NOT NULL,
    PRECO_UNITARIO VARCHAR(20) NOT NULL,
    UNIDADE VARCHAR(10) NOT NULL,
    CNPJ INT,
    CONSTRAINT FK_COMP_FORNECEDOR FOREIGN KEY(CNPJ) REFERENCES FORNECEDORES(CNPJ)
);


ALTER TABLE COMPONENTES ADD TIPO_COMPONENTE VARCHAR(12) NOT NULL;
ALTER TABLE COMPONENTES MODIFY COLUMN TIPO_COMPONENTE VARCHAR(20) NOT NULL;
ALTER TABLE COMPONENTES CHANGE COLUMN TIPO_COMPONENTE CARATER_COMPONENTE VARCHAR(20) NOT NULL;
ALTER TABLE COMPONENTES DROP COLUMN CARATER_COMPONENTE;



CREATE TABLE IF NOT EXISTS TIPO_COMPONENTES(
    NOME_TIPO VARCHAR(45) NOT NULL,
    COD_COMPONENTE INT,
    CONSTRAINT FK_TIPO_COMPONENTE FOREIGN KEY(COD_COMPONENTE) REFERENCES COMPONENTES(COD_COMPONENTE)
);


ALTER TABLE TIPO_COMPONENTES ADD FORMATO_COMPONENTE VARCHAR(12) NOT NULL;
ALTER TABLE TIPO_COMPONENTES MODIFY COLUMN FORMATO_COMPONENTE VARCHAR(20) NOT NULL;
ALTER TABLE TIPO_COMPONENTES CHANGE COLUMN FORMATO_COMPONENTE FORMA_COMPONENTE VARCHAR(20) NOT NULL;
ALTER TABLE TIPO_COMPONENTES DROP COLUMN FORMA_COMPONENTE;



CREATE TABLE IF NOT EXISTS RM(
    DATA_MANUTENCAO DATE NOT NULL,
    DESCRICAO_MANUTENCAO VARCHAR(45) NOT NULL,
    COD_MAQUINA INT,
    CONSTRAINT FK_RM_MAQUINA FOREIGN KEY(COD_MAQUINA) REFERENCES MAQUINAS(COD_MAQUINA)
);


ALTER TABLE RM ADD REGISTRO_FEITO VARCHAR(12) NOT NULL;
ALTER TABLE RM MODIFY COLUMN REGISTRO_FEITO VARCHAR(45) NOT NULL;
ALTER TABLE RM CHANGE COLUMN REGISTRO_FEITO NOTAS_REGISTRO VARCHAR(45) NOT NULL;
ALTER TABLE RM DROP COLUMN NOTAS_REGISTRO;



CREATE TABLE IF NOT EXISTS PESSOAS(
    COD_PESSOAL INT PRIMARY KEY,
    NOME_PESSOA VARCHAR(45),
    IDADE_PESSOA VARCHAR(10)
);


DROP TABLE PESSOAS;
