CREATE DATABASE ESTCASO_2;

USE ESTCASO_2;

CREATE TABLE IF NOT EXISTS PASSAGEIROS(
    CPF INT PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL
);


ALTER TABLE PASSAGEIROS ADD COLUMN SOBRENOME VARCHAR(45) NOT NULL;
ALTER TABLE PASSAGEIROS MODIFY COLUMN SOBRENOME VARCHAR(30) NOT NULL;
ALTER TABLE PASSAGEIROS CHANGE COLUMN SOBRENOME SURNAME VARCHAR(30)
NOT NULL;
ALTER TABLE PASSAGEIROS DROP COLUMN SURNAME;


CREATE TABLE IF NOT EXISTS AERONAVES(
    ID_AERONAVE INT PRIMARY KEY,
    INFO_AERONAVE VARCHAR(45) NOT NULL,
    CAPACIDADE VARCHAR(45) NOT NULL,
    VOOS_DIA VARCHAR(45) NOT NULL,
    VOOS_SEMANA VARCHAR(45) NOT NULL
);


ALTER TABLE AERONAVES ADD COLUMN MODELO VARCHAR(45) NOT NULL;
ALTER TABLE AERONAVES MODIFY COLUMN MODELO VARCHAR(30) NOT NULL;
ALTER TABLE AERONAVES CHANGE COLUMN MODELO MODEL VARCHAR(30)
NOT NULL;
ALTER TABLE AERONAVES DROP COLUMN MODEL;


CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
    ID_FUNCIONARIO INT PRIMARY KEY,
    NOME_FUNCIONARIO VARCHAR(45) NOT NULL,
    CARGO_FUNCIONARIO VARCHAR(45) NOT NULL
);


ALTER TABLE FUNCIONARIOS ADD COLUMN SOBRENOME VARCHAR(45) NOT NULL;
ALTER TABLE FUNCIONARIOS MODIFY COLUMN SOBRENOME VARCHAR(30) NOT NULL;
ALTER TABLE FUNCIONARIOS CHANGE COLUMN SOBRENOME SURNAME VARCHAR(30)
NOT NULL;
ALTER TABLE FUNCIONARIOS DROP COLUMN SURNAME;



CREATE TABLE IF NOT EXISTS AEROPORTOS(
    ID_AEROPORTO INT PRIMARY KEY,
    NOME_AEROPORTO VARCHAR(45) NOT NULL,
    LOCAL_AEROPORTO VARCHAR(45) NOT NULL,
    ID_AERONAVE INT,
    CONSTRAINT FK_AEROPRT_AERONV FOREIGN KEY(ID_AERONAVE) REFERENCES
    AERONAVES(ID_AERONAVE)
);


ALTER TABLE AEROPORTOS ADD COLUMN VAGAS VARCHAR(45) NOT NULL;
ALTER TABLE AEROPORTOS MODIFY COLUMN VAGAS VARCHAR(30) NOT NULL;
ALTER TABLE AEROPORTOS CHANGE COLUMN VAGAS PARKING_SPOT VARCHAR(30)
NOT NULL;
ALTER TABLE AEROPORTOS DROP COLUMN PARKING_SPOT;


CREATE TABLE IF NOT EXISTS VOOS(
    ID_VOO INT PRIMARY KEY,
    ORIGEM_VOO VARCHAR(45) NOT NULL,
    DESTINO_VOO VARCHAR(45) NOT NULL,
    HORA_PARTIDA DATETIME NOT NULL,
    HORA_CHEGADA DATETIME NOT NULL,
    ID_RESERVA INT
);


ALTER TABLE VOOS ADD COLUMN NOME_PILOTO VARCHAR(45) NOT NULL;
ALTER TABLE VOOS MODIFY COLUMN NOME_PILOTO VARCHAR(30) NOT NULL;
ALTER TABLE VOOS CHANGE COLUMN NOME_PILOTO NAME_OF_PILOT VARCHAR(30)
NOT NULL;
ALTER TABLE VOOS DROP COLUMN NAME_OF_PILOT;


CREATE TABLE IF NOT EXISTS RESERVAS(
    ID_RESERVA INT PRIMARY KEY,
    INFO_RESERVA VARCHAR(45) NOT NULL,
    STATUS_RESERVA VARCHAR(45) NOT NULL,
    CPF INT,
    ID_VOO INT,
    CONSTRAINT FK_RESERVA_PSSG FOREIGN KEY(CPF) REFERENCES PASSAGEIROS(CPF),
    CONSTRAINT FK_RESERVA_VOO FOREIGN KEY(ID_VOO) REFERENCES VOOS(ID_VOO)
);


ALTER TABLE RESERVAS ADD COLUMN QNTD_RESERVAS VARCHAR(45) NOT NULL;
ALTER TABLE RESERVAS MODIFY COLUMN QNTD_RESERVAS VARCHAR(30) NOT NULL;
ALTER TABLE RESERVAS CHANGE COLUMN QNTD_RESERVAS AMOUNT_BOOKINGS VARCHAR(30) NOT NULL;
ALTER TABLE RESERVAS DROP COLUMN AMOUNT_BOOKINGS;


ALTER TABLE VOOS ADD CONSTRAINT FK_VOOS_RSRV FOREIGN KEY(ID_RESERVA) REFERENCES RESERVAS(ID_RESERVA);


CREATE TABLE IF NOT EXISTS ENDERECO(
    ID_ENDERECO INT PRIMARY KEY,
    UF VARCHAR(2) NOT NULL,
    CEP VARCHAR(11) NOT NULL,
    CIDADE VARCHAR(45) NOT NULL,
    BAIRRO VARCHAR(45) NOT NULL,
    LOGRADOURO VARCHAR(45) NOT NULL,
    COMPLEMENTO VARCHAR(45) NOT NULL,
    NUMERO VARCHAR(10) NOT NULL,
    CPF INT,
    CONSTRAINT FK_ENDERECO_PSSG FOREIGN KEY(CPF) REFERENCES PASSAGEIROS(CPF)
);


ALTER TABLE ENDERECO ADD COLUMN TIPO_MORADIA VARCHAR(45) NOT NULL;
ALTER TABLE ENDERECO MODIFY COLUMN TIPO_MORADIA VARCHAR(30) NOT NULL;
ALTER TABLE ENDERECO CHANGE COLUMN TIPO_MORADIA HOUSING_TYPE VARCHAR(30) NOT NULL;
ALTER TABLE ENDERECO DROP COLUMN HOUSING_TYPE;


CREATE TABLE IF NOT EXISTS TELEFONE(
    ID_TELEFONE INT PRIMARY KEY,
    NUMERO_TELEFONE VARCHAR(45) NOT NULL,
    CPF INT,
    CONSTRAINT FK_TELEFONE_PSSG FOREIGN KEY(CPF) REFERENCES PASSAGEIROS(CPF)
);

ALTER TABLE TELEFONE ADD COLUMN DDD VARCHAR(45) NOT NULL;
ALTER TABLE TELEFONE MODIFY COLUMN DDD VARCHAR(30) NOT NULL;
ALTER TABLE TELEFONE CHANGE COLUMN DDD AREA_CODE VARCHAR(30) NOT NULL;
ALTER TABLE TELEFONE DROP COLUMN AREA_CODE;

CREATE TABLE IF NOT EXISTS PESSOAS(
    ID_PESSOA INT PRIMARY KEY,
    CEP_PESSOA VARCHAR(45) NOT NULL
);

DROP TABLE IF EXISTS PESSOAS;

