CREATE DATABASE ESTCASO_4;

USE ESTCASO_4;

CREATE TABLE IF NOT EXISTS ALUNOS(
    CPF INT PRIMARY KEY,
    NOME_ALUNO VARCHAR(45) NOT NULL,
    DATA_NASC DATE NOT NULL,
    MODALIDADE_INTERESSE VARCHAR(45) NOT NULL
);


ALTER TABLE ALUNOS ADD COLUMN SOBRENOME VARCHAR(45) NOT NULL;
ALTER TABLE ALUNOS MODIFY COLUMN SOBRENOME VARCHAR(30) NOT NULL;
ALTER TABLE ALUNOS CHANGE COLUMN SOBRENOME SURNAME VARCHAR(30) NOT NULL;
ALTER TABLE ALUNOS DROP COLUMN SURNAME; 


CREATE TABLE IF NOT EXISTS MODALIDADES(
    ID_MODALIDADE INT PRIMARY KEY,
    NOME_MODALIDADE VARCHAR(45) NOT NULL,
    QNTD_ALUNOS VARCHAR(45) NOT NULL,
    CPF INT,
    CONSTRAINT FK_MODALIDADES_ALUNO FOREIGN KEY(CPF) REFERENCES ALUNOS(CPF)
);


ALTER TABLE MODALIDADES ADD COLUMN ATIVIDADE VARCHAR(45) NOT NULL;
ALTER TABLE MODALIDADES MODIFY COLUMN ATIVIDADE VARCHAR(30) NOT NULL;
ALTER TABLE MODALIDADES CHANGE COLUMN ATIVIDADE ACTIVITY VARCHAR(30) NOT NULL;
ALTER TABLE MODALIDADES DROP COLUMN ACTIVITY; 


CREATE TABLE IF NOT EXISTS INSTRUTORES(
    ID_INSTRUTOR INT PRIMARY KEY,
    NOME_INSTRUTOR VARCHAR(45) NOT NULL,
    ID_MODALIDADE INT,
    CPF INT,
    CONSTRAINT FK_INSTRUTOR_MDLD FOREIGN KEY(ID_MODALIDADE) REFERENCES MODALIDADES(ID_MODALIDADE),
    CONSTRAINT FK_INSTRUTOR_ALUNO FOREIGN KEY(CPF) REFERENCES ALUNOS(CPF)
);


ALTER TABLE INSTRUTORES ADD COLUMN SOBRENOME VARCHAR(45) NOT NULL;
ALTER TABLE INSTRUTORES MODIFY COLUMN SOBRENOME VARCHAR(30) NOT NULL;
ALTER TABLE INSTRUTORES CHANGE COLUMN SOBRENOME SURNAME VARCHAR(30) NOT NULL;
ALTER TABLE INSTRUTORES DROP COLUMN SURNAME; 


CREATE TABLE IF NOT EXISTS PLANOS_TREINAMENTO(
    ID_PLANO INT PRIMARY KEY,
    DESCRICAO VARCHAR(45) NOT NULL,
    ID_INSTRUTOR INT,
    CPF INT,
    CONSTRAINT FK_TREINO_INSTRUTOR FOREIGN KEY(ID_INSTRUTOR) REFERENCES INSTRUTORES(ID_INSTRUTOR),
    CONSTRAINT FK_TREINO_ALUNO FOREIGN KEY(CPF) REFERENCES ALUNOS(CPF)
);


ALTER TABLE PLANOS_TREINAMENTO ADD COLUMN TREINO VARCHAR(45) NOT NULL;
ALTER TABLE PLANOS_TREINAMENTO MODIFY COLUMN TREINO VARCHAR(30) NOT NULL;
ALTER TABLE PLANOS_TREINAMENTO CHANGE COLUMN TREINO TRAINING VARCHAR(30) NOT NULL;
ALTER TABLE PLANOS_TREINAMENTO DROP COLUMN TRAINING; 


CREATE TABLE IF NOT EXISTS AULAS(
    ID_AULA INT NOT NULL,
    HORARIO_AULA TIME NOT NULL,
    CAPACIDADE_AULA VARCHAR(45) NOT NULL,
    ID_INSTRUTOR INT,
    CPF INT,
    CONSTRAINT FK_AULA_INSTRUTOR FOREIGN KEY(ID_INSTRUTOR) REFERENCES INSTRUTORES(ID_INSTRUTOR),
    CONSTRAINT FK_AULA_ALUNO FOREIGN KEY(CPF) REFERENCES ALUNOS(CPF)
);


ALTER TABLE AULAS ADD COLUMN NOME_AULA VARCHAR(45) NOT NULL;
ALTER TABLE AULAS MODIFY COLUMN NOME_AULA VARCHAR(30) NOT NULL;
ALTER TABLE AULAS CHANGE COLUMN NOME_AULA NAME_CLASS VARCHAR(30) NOT NULL;
ALTER TABLE AULAS DROP COLUMN NAME_CLASS; 


CREATE TABLE IF NOT EXISTS PAGAMENTOS(
    ID_PAGAMENTO INT PRIMARY KEY,
    DATA_PAGAMENTO DATETIME NOT NULL,
    VALOR_PAGAMENTO VARCHAR(45) NOT NULL,
    STATUS_PAGAMENTO VARCHAR(45) NOT NULL,
    CPF INT,
    CONSTRAINT FK_PAGAMENTO_ALUNO FOREIGN KEY(CPF) REFERENCES ALUNOS(CPF)
);


ALTER TABLE PAGAMENTOS ADD COLUMN E_O_PIX VARCHAR(45) NOT NULL;
ALTER TABLE PAGAMENTOS MODIFY COLUMN E_O_PIX VARCHAR(30) NOT NULL;
ALTER TABLE PAGAMENTOS CHANGE COLUMN E_O_PIX PIX VARCHAR(30) NOT NULL;
ALTER TABLE PAGAMENTOS DROP COLUMN PIX; 


CREATE TABLE IF NOT EXISTS ENDERECO(
    CEP VARCHAR(45) NOT NULL,
    CIDADE VARCHAR(45) NOT NULL,
    BAIRRO VARCHAR(45) NOT NULL,
    NOME_RUA VARCHAR(45) NOT NULL,
    NUM_RUA VARCHAR(45) NOT NULL,
    LOGRADOURO VARCHAR(45) NOT NULL,
    CPF INT,
    CONSTRAINT FK_ENDERECO_CLIENTE FOREIGN KEY(CPF) REFERENCES ALUNOS(CPF)
);

ALTER TABLE ENDERECO ADD COLUMN PAIS VARCHAR(45);
ALTER TABLE ENDERECO MODIFY COLUMN PAIS VARCHAR (60);
ALTER TABLE ENDERECO CHANGE COLUMN PAIS COUNTRY VARCHAR(60);
ALTER TABLE ENDERECO DROP COLUMN COUNTRY;

CREATE TABLE IF NOT EXISTS PESSOAS(
    ID_PESSOA INT PRIMARY KEY,
    CEP_PESSOA VARCHAR(45) NOT NULL
);

DROP TABLE IF EXISTS PESSOAS;
