CREATE DATABASE EXERCICIO1;
USE EXERCICIO1;

CREATE TABLE IF NOT EXISTS PARTICIPANTES(
NUM_INSCRICAO INT,
CPF VARCHAR(14),
PRIMARY KEY(NUM_INSCRICAO,CPF),
NOME VARCHAR(100) NOT NULL,
DATA_NASC DATE NOT NULL,
EMPRESA VARCHAR(100)
);

ALTER TABLE PARTICIPANTES
ADD COLUMN IDADE INT;

ALTER TABLE PARTICIPANTES 
MODIFY COLUMN IDADE INT NOT NULL;

ALTER TABLE PARTICIPANTES
CHANGE COLUMN IDADE NASCIMENTO INT NOT NULL;

ALTER TABLE PARTICIPANTES
DROP COLUMN NASCIMENTO;


CREATE TABLE IF NOT EXISTS LOCAIS(
ID_LOCAL INT PRIMARY KEY,
NOME_LOCAL VARCHAR(100) NOT NULL,
LOG_LOCAL VARCHAR(100) NOT NULL,
NUMLOG_LOCAL INT,
BAIRRO_LOCAL VARCHAR(100) NOT NULL,
CIDADE VARCHAR(100) NOT NULL,
UF CHAR(2) NOT NULL,
CEP VARCHAR(20) NOT NULL,
CAPACIDADE INT NOT NULL);

ALTER TABLE LOCAIS
ADD COLUMN PAIS VARCHAR(20);

ALTER TABLE LOCAIS
MODIFY COLUMN PAIS VARCHAR(30) NOT NULL;

ALTER TABLE LOCAIS
CHANGE COLUMN PAIS COUNTRY VARCHAR(30) NOT NULL;

ALTER TABLE LOCAIS
DROP COLUMN COUNTRY;

CREATE TABLE IF NOT EXISTS EVENTOS(
ID_EVENTO INT PRIMARY KEY,
NOME_EVENTO VARCHAR(100) NOT NULL,
DATA_EVENTO DATE NOT NULL,
ENTIDADE_EVENTO VARCHAR(100) NOT NULL,
LOCAL_EVENTO INT,
FOREIGN KEY (LOCAL_EVENTO) REFERENCES LOCAIS(ID_LOCAL));

ALTER TABLE EVENTOS
ADD COLUMN DUVIDAS_EVENTO VARCHAR(20);

ALTER TABLE EVENTOS
MODIFY COLUMN DUVIDAS_EVENTO VARCHAR(45) NOT NULL;

ALTER TABLE EVENTOS
CHANGE COLUMN DUVIDAS_EVENTO QUESTIONARIO VARCHAR(45) NOT NULL;

ALTER TABLE EVENTOS
DROP COLUMN QUESTIONARIO;

CREATE TABLE IF NOT EXISTS ATIVIDADES(
ID_ATIVIDADE INT PRIMARY KEY,
NOME_ATV VARCHAR(100) NOT NULL,
DATA_ATV DATE NOT NULL,
HORA_ATV TIME NOT NULL,
EVENTO_ATV INT NOT NULL,
FOREIGN KEY(EVENTO_ATV) REFERENCES EVENTOS(ID_EVENTO));

ALTER TABLE ATIVIDADES
ADD COLUMN CARATER_ATV VARCHAR(45);

ALTER TABLE ATIVIDADES
MODIFY COLUMN CARATER_ATV VARCHAR(45) NOT NULL;

ALTER TABLE ATIVIDADES
CHANGE COLUMN CARATER_ATV MODALIDADE_ATV VARCHAR(45) NOT NULL;

ALTER TABLE ATIVIDADES
DROP COLUMN MODALIDADE_ATV;

CREATE TABLE IF NOT EXISTS PARTICIPANTE_EVENTO(
PE_INSCRICAO INT,
PE_CPF VARCHAR(14),
PE_EVENTO INT,
PRIMARY KEY(PE_INSCRICAO,PE_CPF,PE_EVENTO),
FOREIGN KEY(PE_INSCRICAO,PE_CPF) REFERENCES PARTICIPANTES(NUM_INSCRICAO,CPF),
FOREIGN KEY(PE_EVENTO) REFERENCES EVENTOS(ID_EVENTO));

ALTER TABLE PARTICIPANTE_EVENTO
ADD COLUMN PE_ORIGEM VARCHAR(20);

ALTER TABLE PARTICIPANTE_EVENTO
MODIFY COLUMN PE_ORIGEM VARCHAR(30) NOT NULL;

ALTER TABLE PARTICIPANTE_EVENTO
CHANGE COLUMN PE_ORIGEM NACIONALIDADE VARCHAR(30) NOT NULL;

ALTER TABLE PARTICIPANTE_EVENTO
DROP COLUMN NACIONALIDADE;

CREATE TABLE IF NOT EXISTS PARTICIPANTE_ATIVIDADE(
PA_INSCRICAO INT,
PA_CPF VARCHAR(14),
PA_ATIVIDADE INT,
PRIMARY KEY(PA_INSCRICAO,PA_CPF,PA_ATIVIDADE),
FOREIGN KEY(PA_INSCRICAO,PA_CPF) REFERENCES PARTICIPANTES(NUM_INSCRICAO,CPF),
FOREIGN KEY(PA_ATIVIDADE) REFERENCES ATIVIDADES(ID_ATIVIDADE));

ALTER TABLE PARTICIPANTE_ATIVIDADE
ADD COLUMN ATIVIDADE_ESCOLHIDA VARCHAR(20);

ALTER TABLE PARTICIPANTE_ATIVIDADE
MODIFY COLUMN ATIVIDADE_ESCOLHIDA VARCHAR(45) NOT NULL;

ALTER TABLE PARTICIPANTE_ATIVIDADE
CHANGE COLUMN ATIVIDADE_ESCOLHIDA ESPORTE VARCHAR(45) NOT NULL;

ALTER TABLE PARTICIPANTE_ATIVIDADE
DROP COLUMN ESPORTE;

CREATE TABLE IF NOT EXISTS PESSOAS(
    ID_PESSOA INT PRIMARY KEY,
    CEP_PESSOA VARCHAR(45) NOT NULL
);

DROP TABLE IF EXISTS PESSOAS;
